import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Portfólio - Leonardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className="antialiased bg-background text-foreground"
      >
        
        <Providers>
          
          {children}
        </Providers>
      </body>
    </html>
  );
}
